Repository rubenlagus/TelegramBots, pull requests merged in 2018-05, with the labels that each got.

#460 fix field name pending_update_count of WebhookInfo
  telegrambots-meta/src/main/java/org/telegram/telegrambots/api/objects/WebhookInfo.java
Labels: Ready to merge

#456 Spring boot start config
  telegrambots-spring-boot-starter/pom.xml
  telegrambots-spring-boot-starter/src/main/java/org/telegram/telegrambots/starter/TelegramBotStarterConfiguration.java
  telegrambots-spring-boot-starter/src/test/java/org/telegram/telegrambots/starter/TestTelegramBotStarterConfiguration.java
Labels: Ready to merge

#454 Add detailed constructor, equals and hashCode to User object
  telegrambots-meta/src/main/java/org/telegram/telegrambots/api/objects/User.java
Labels: Ready to merge

#452 Fix group update check for GROUP_ADMIN
  telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/bot/AbilityBot.java
  telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/objects/Flag.java
  telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/util/AbilityUtils.java
  telegrambots-abilities/src/test/java/org/telegram/abilitybots/api/bot/AbilityBotTest.java
Labels: Abilities, Ready to merge

#466 Expose abilities and replies, add report command and reformat /commands, closes #436
  TelegramBots.wiki/abilities/Simple-Example.md
  telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/bot/AbilityBot.java
  telegrambots-abilities/src/main/resources/messages.properties
  telegrambots-abilities/src/test/java/org/telegram/abilitybots/api/bot/AbilityBotI18nTest.java
  telegrambots-abilities/src/test/java/org/telegram/abilitybots/api/bot/AbilityBotTest.java
  telegrambots-abilities/src/test/resources/messages_it_IT.properties
Labels: Abilities
